# Whimperizer Configuration
api:
  # Default provider: openai, anthropic, google
  default_provider: "openai"
  
  # Provider-specific settings
  providers:
    openai:
      base_url: "https://api.openai.com/v1"
      model: "gpt-4.1"
      max_tokens: 327680
      temperature: 0.7
    
    anthropic:
      base_url: "https://api.anthropic.com"
      model: "claude-3-sonnet-20240229"
      max_tokens: 4000
      temperature: 0.7
    
    google:
      base_url: "https://generativelanguage.googleapis.com"
      model: "gemini-pro"
      max_tokens: 4000
      temperature: 0.7

processing:
  input_dir: "downloaded_content"
  output_dir: "whimperized_content"
  
# File naming patterns
patterns:
  input_file: "{group1}-{group2}-{line}.txt"
  output_file: "{group1}-{group2}-whimperized.txt"

# Processing options
options:
  combine_by_group: true  # Combine all files from same group1+group2 combination
  sort_by_line: true      # Process files in line number order within each group 