[build]
  # Build settings
  publish = "dist"
  command = "npm run build"

[build.environment]
  # Node version for build
  NODE_VERSION = "18"

# Redirect all routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API proxy for development (optional - for connecting to local backend)
[[redirects]]
  from = "/api/*"
  to = "http://localhost:8000/api/:splat"
  status = 200
  force = false
  condition = "env=development"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"