# Portkey Gateway Configuration
providers:
  openai:
    api_key: "${OPENAI_API_KEY}"
    base_url: "https://api.openai.com/v1"
  
  anthropic:
    api_key: "${ANTHROPIC_API_KEY}"
    base_url: "https://api.anthropic.com"
    
  google:
    api_key: "${GOOGLE_API_KEY}"
    base_url: "https://generativelanguage.googleapis.com"

# Default settings
settings:
  default_provider: "openai"
  timeout: 30
  retries: 3
  log_level: "INFO"

# Rate limiting (optional)
rate_limits:
  openai:
    requests_per_minute: 60
    tokens_per_minute: 90000
  anthropic:
    requests_per_minute: 50
    tokens_per_minute: 40000
  google:
    requests_per_minute: 60
    tokens_per_minute: 32000